### ISSUE TITLE
【bug】thinkphp下会出现mysql 字段解析 错误

### ISSUE THREAD

**Issue by exvu** [yanwenwu/migration-generator#11]
1.  原来数据库的字段是text被解析成MediumText
`php
[
'limit' => MysqlAdapter::TEXT_MEDIUM,//应该是TEXT_REGULAR
]
`

2.  有符号的decimal 解析成无符号
`php
[
signed' => false,
]
`
3. 生成的文件是0加时间戳作为前缀，结合think-migration执行 run后再依次回滚，最开始的两个文件不rollback
比如有22个数据库文件 020200923005536 120200923005536 220200923005536.。。。2120200923005536
只有前两个不会回滚 修改名称后 run再rollback就能回滚
@ @yanwenwu

**Comment by JaguarJack** [comment]
1. 已修复
2 本地测试没有问题
3 自定义命令提供 demo 命令，如果不满足的话，你只有自己根据 demo 命令来实现。
