### ISSUE TITLE
缺少的 SimpleArrayType 应该是set多选类型 附上文件

### ISSUE THREAD

**Issue by ninetian** [yanwenwu/migration-generator#17]
把这个内容 
https://gist.githubusercontent.com/ninetian/2edc5458a3bbc460e978eb496f0923d5/raw/fd661d4bc9357554b6f66bb917e30b0e5b7b9fd7/gistfile1.txt
保存为  SimpleArrayType.php 

上传至 vendor/jaguarjack/migration-generator/src/Migration/Columns/Thinkphp 下面

然后在

`sudo -u www php think migration:generate`

应该就没有问题了

**Comment by JaguarJack** [comment]
兄弟 提交 PR 啊
