### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by yangweijie** [yanwenwu/migration-generator#2]
![image](https://user-images.githubusercontent.com/1614114/74996355-494b9200-548e-11ea-8736-0ba62ea76c57.png)
![image](https://user-images.githubusercontent.com/1614114/74996360-4cdf1900-548e-11ea-9166-6963b72b27c7.png)

**Comment by JaguarJack** [comment]
composer require jaguarjack/migration-generator 1.0

**Comment by he426100** [comment]
> composer require jaguarjack/migration-generator 1.0

安装不了
