### ISSUE TITLE
添加下类型

### ISSUE THREAD

**Issue by jiayang007** [yanwenwu/migration-generator#20]
\JaguarJack\MigrateGenerator\Migration\Columns\Thinkphp\DateTimeType not found

**Comment by zyimm** [comment]
DateTimeType 是有的 源文件 名称和类型名 DatetimeType 修改为 DateTimeType 就行了

**Comment by zyimm** [comment]
> \JaguarJack\MigrateGenerator\Migration\Columns\Thinkphp\DateTimeType not found
DateTimeType 是有的 源文件 名称和类型名 DatetimeType 修改为 DateTimeType 就行了
