### ISSUE TITLE
单表怎么生成？

### ISSUE THREAD

**Issue by wlzxdm** [yanwenwu/migration-generator#23]
您好，问下单表怎么生成？全部生成已经有的不会覆盖，每次都新加。

**Comment by JaguarJack** [comment]
```php
       $migrateGenerator = (new MigrateGenerator('laravel'));

        $tables = $migrateGenerator->getDatabase()->getAllTables();

        foreach ($tables as $key => $table) {

            file_put_contents(database_path( 'migrations/')  . date('Y_m_d_His') . '_' . $table->getName(). '.php' ,

                $migrateGenerator->getMigrationContent($table));

            $this->info(sprintf('%s table migration file generated', $table->getName()));
        }

```
目前没有单独生成的 command，但是你可以根绝上面的代码，单独写一个单表生成的，只需要给出表名就行

**Comment by wlzxdm** [comment]
好的，明白了，谢谢🙏wlzxdm在 2023年5月1日，20:05，JaguarJack ***@***.***> 写道：﻿
       $migrateGenerator = (new MigrateGenerator('laravel'));

        $tables = $migrateGenerator->getDatabase()->getAllTables();

        foreach ($tables as $key => $table) {

            file_put_contents(database_path( 'migrations/')  . date('Y_m_d_His') . '_' . $table->getName(). '.php' ,

                $migrateGenerator->getMigrationContent($table));

            $this->info(sprintf('%s table migration file generated', $table->getName()));
        }
目前没有单独生成的 command，但是你可以根绝上面的代码，单独写一个单表生成的，只需要给出表名就行
