### ISSUE TITLE
执行 php think migration:gererate

### ISSUE THREAD

**Issue by sinner2046** [yanwenwu/migration-generator#8]
call_user_func_array() expects parameter 1 to be a valid callback, class 'think\db\connector\Mysql' does not have a method 'getConnection'

**Comment by JaguarJack** [comment]
这个是 thinkphp 删除了 db 的 getConnection 方法了，降一下你的 ORM 版本

**Comment by sinner2046** [comment]
降到2.0.31么? 我 tp 是最新的, 会不会影响别的功能

**Comment by JaguarJack** [comment]
你可以先降回去，生成之后再升回去。这个我没办法的，因为 tp 扩展底层方法经常改动，版本之间又不一致，我改了也毫无意义。等过段时间稳定了，再修改

**Comment by fredyzhang5532** [comment]
具体怎么操作
[TypeError]
  call_user_func_array() expects parameter 1 to be a valid callback, class 't
  hink\db\connector\Mysql' does not have a method 'getConnection'

**Comment by JaguarJack** [comment]
> 具体怎么操作
> [TypeError]
> call_user_func_array() expects parameter 1 to be a valid callback, class 't
> hink\db\connector\Mysql' does not have a method 'getConnection'

如果是 6.0.3 版本，降低到 6.0.2，在执行命令，最后如果需要就升回去

**Comment by fredyzhang5532** [comment]
> > 具体怎么操作
> > [TypeError]
> > call_user_func_array() expects parameter 1 to be a valid callback, class 't
> > hink\db\connector\Mysql' does not have a method 'getConnection'
> 
> 如果是 6.0.3 版本，降低到 6.0.2，在执行命令，最后如果需要就升回去

我降到6.0.2还是不行,不会降到5.1吧,我看文档RC4（2019年8月16日）就取消了getConnection

**Comment by fredyzhang5532** [comment]
我降到6.0.2还是不行,不会降到5.1吧,我看文档RC4（2019年8月16日）就取消了getConnection

**Comment by JaguarJack** [comment]
> > > 具体怎么操作
> > > [TypeError]
> > > call_user_func_array() expects parameter 1 to be a valid callback, class 't
> > > hink\db\connector\Mysql' does not have a method 'getConnection'
> > 
> > 
> > 如果是 6.0.3 版本，降低到 6.0.2，在执行命令，最后如果需要就升回去
> 
> 我降到6.0.2还是不行,不会降到5.1吧,我看文档RC4（2019年8月16日）就取消了getConnection

不太可能 因为我就在用。运行在0.2版本，
你需要降低的是 think-orm 版本
